name: Publish and bundle Lua scripts
run-name: ${{ github.actor }} is publishing and bundling Lua scripts
on: [workflow_dispatch]
jobs:
  get_version:
    uses: ./.github/workflows/get_version.yml

  bundle:
    name: Bundle Scripts
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
              node-version: 20
        - run: npm ci
        - run: npm run
        - name: "Upload Artifacts"
          uses: actions/upload-artifact@v4
          with:
            name: artifacts
            path: |
              *
              */*
              */*/*

  create_release_draft:
    needs: [ get_version, bundle ]
    runs-on: ubuntu-latest
    steps:
      - name: "Download Artifacts"
        uses: actions/download-artifact@v4
      - name: "Create Release"
        uses: softprops/action-gh-release@v2
        with:
          name: "Release ${{ needs.get_version.outputs.version }}"
          tag_name: "v${{ needs.get_version.outputs.version }}"
          body: "TODO: Write Changelog"
          draft: true
          prerelease: true
          fail_on_unmatched_files: true
          files: | 
            ./artifacts/*
            ./artifacts/*/*
            ./artifacts/*/*/*
